---
  - hosts: arvan
    gather_facts: false
    become: true
    remote_user: ubuntu
    tasks:
      - name: Generate SSL for domain.
        tags: generate
        ansible.builtin.command: 
          chdir: /opt/simple-docker-app
          cmd: >
            docker compose run --rm certbot certonly
            --webroot --webroot-path /var/www/certbot/
            -d siavashfazli.ir --email siavashfazlikhalaf@gmail.com
            --agree-tos --eff-email --force-renewal 

      - name: Append SSL block to nginx conf file.
        ansible.builtin.command: 
          chdir: /opt/simple-docker-app/conf.d
          cmd: echo SSL_block.conf.temp >> web_app.conf

      - name: Restart Nginx container (web_app)
        community.docker.docker_compose:
          project_src: /opt/simple-docker-app/
          build: false
          restarted: true
          
      - name: Create a cron job for Certbot renewal.
        tags: renew
        cron:
          cron_file: /etc/cron.d/renew
          name: "SSL Renew"
          minute: "0"
          hour: "0"
          day: "1"
          month: "*/1"  # Run every month
          weekday: "*"
          user: root
          job: "docker-compose -f /opt/simple-docker-app/docker-compose.yml run --rm certbot renew"
