---
- hosts: arvan
  gather_facts: false
  become: true
  tasks:
    - name: Install docker and docker-compose python library.
      ansible.builtin.pip:
        name: 
          - docker==6.1.3
          - docker-compose
    - name: Clone a github repository
      tags: git
      git:
       repo: https://github.com/siavashfazli/simple-docker-app.git
       dest: /opt/simple-docker-app
       clone: yes
       update: yes

    - name: Create network
      community.docker.docker_network:
        name: nginx    
    
    - name: Start web_app container.
      tags: container
      community.docker.docker_compose:
        project_src: /opt/simple-docker-app/
        files:
          - docker-compose.yml
